version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 231703
  backend:
    container_name: backend
    build: ./shelter-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 231703
      SPRING_CORS_ALLOWED_ORIGINS: '*'
  frontend:
    container_name: frontend
    build: ./shelter-frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
